# Generated by Django 5.0.7 on 2024-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('answer', 'Answer'), ('signal', 'Signal')], max_length=10),
        ),
    ]
