# Generated by Django 5.0.7 on 2024-08-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('notification_type', 'related_object_id', 'sender', 'recipient')},
        ),
    ]
