# Generated by Django 5.0.7 on 2024-08-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
